sudo: required
services:
- docker
before_install:
- sudo apt-get update && sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=1.10.3-0~trusty
script:
- make bintray.json
deploy:
  on: master
  provider: bintray
  file: bintray.json
  user: EvanKrall
  key:
    secure: QqL+FE094iZZEd47jXizzpLXE8zg0i+FTGV9Bc5/fjtI0xUyriU8pLD79RiNuFNhzsfI/AcJOyoYQRFUN81dzwTmCO3tfqapW8itWB1Bch1ovuqVD/LeXvbfJ2s1jh6Tkt2soilESFJgCK2nZHFMQKoXFZdCM7tL1RzsuffchUbMUfIIdc44VO+Qios5sfBKbpwEGY9UDfY/a0y96LYbQvG4OVSC2LNJb7p932+PPvNyNKXEnBr6L6iRZl7jATX3G5ka6lbn7/tAq0KO3s2tz+IHUDFX50QtJB849DN7Jy/SHSVridrpu/K3Hy/KKPYctpyehpxl10vY+cSH+5LCk1IVg7uWWYhM9eU0gP90VkE4nzoiQdInmudB+pLwXaGMaCTx3SkEiTvCe0lbCV3S055mV/4yxLpf6K+UJaWXUN10kBBQWQ5qUSXGcKKAHkALTl9CQUHIp028hS1SKQ+PZ8RBwDzqUd5z2kan8kd7HSyUxg81eZegeyhSmwtqATwHGLfrdCwjDa1SoNagx6dLXD9zK3Le3LephUfSvn9e8xfQm5cBTa1TJR9DeSbiy+l3/g/o4YfoCjX/bLYe0aDJYAbRTyz4Zfltvz3mGJeT3UFv8taNic5J6jGatxYjJnJpCHS5m7ozmU7BZttHhnWmlzmwh1qgyvW8drXBUakwZjc=
